### ISSUE TITLE
파일이 없는 것 같습니다.

### ISSUE THREAD

**Issue by NJiHyeon** [Beomi/KcBERT#18]
안녕하세요! 좋은 모델 너무 감사합니다!
다름이 아니라 제가 가진 데이터셋으로 추가 학습시키려고 하는데 run_mlm.py 파일이 없는 것 같습니다.
혹시 실례가 안된다면 파일을 받을 수 있을까요 ? ㅜㅜ
감사합니다.

**Comment by Beomi** [comment]
안녕하세요.
본 모델은 해당 파일을 사용해 학습한 모델이 아닙니다.

다만, 말씀하시는 파일은 아래 링크 파일인 것으로 추정됩니다.
https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py

도움이 되었으면 싶네요 :)
