### ISSUE TITLE
pretraining 관련 문의

### ISSUE THREAD

**Issue by nawnoes** [Beomi/KcBERT#2]
안녕하세요.
먼저 좋은 프로젝트 및 데이터 공유해주셔서 감사합니다!

캐글에 올려주신 데이터 확인해보니 댓글들 간에 맥락은 따로 없는 것처럼 보여서
기본 버트의 NSP나 알버트의 SOP는 사용하기 어려울것으로 보이는데,
pretraining 시, MLM만 사용하여 학습 하셨는지 여쭤보고 싶습니다.

감사합니다!

**Comment by Beomi** [comment]
안녕하세요,
해당하는 부분에 있어서 MLM과 NSP모두 사용은 되었습니다.
댓글 특성상 확실히 NSP Loss는 큰 의미가 없다고 생각합니다만, 
다만 대부분 한 기사 내 순서대로 작성되어서 NSP Loss는 같은 기사에 쓰였는지 정도로만 잡혔을 거라고 생각합니다 :)
