### ISSUE TITLE
ckpt 에서 BERT 모델 로드하는 방법

### ISSUE THREAD

**Issue by HwangYoonSeob** [Beomi/KcBERT#5]
좋은 자료 공유 감사드립니다.

개인 데이터로 학습시킨 후, 생긴 ckpt 를 BERT 모델에 load 하는 방법에서 막혔습니다 ㅜㅜ 

혹시 가이드라인을 제시해주실 수 있을까요?

**Comment by Beomi** [comment]
안녕하세요,
TPU로 학습한 뒤에 ckpt 파일을 로드하고싶으신걸까요?

**Comment by HwangYoonSeob** [comment]
네 맞습니다

**Comment by Beomi** [comment]
해당부분도 정리해서 올려보겠습니다.
만약 급하시면 https://monologg.kr/2020/05/01/transformers-porting/
위 블로그를 참고해보시면 쉽게 변환하실수 있습니다 :)

**Comment by HwangYoonSeob** [comment]
덕분에 잘 해결했습니다 감사합니다!
