### ISSUE TITLE
kcbert-large colab에서 오류가 발생합니다

### ISSUE THREAD

**Issue by woodongk** [Beomi/KcBERT#6]
![캡처](https://user-images.githubusercontent.com/20855305/100980034-fc056080-3587-11eb-9c47-b38531bef7b0.PNG)

안녕하세요. 올려주신 코드 잘 사용하고 있습니다.

코랩에서 large 파일을 돌리려고 하는데, 일주일 전까지만 해도 잘 작동되다가 갑자기 오류가 발생하네요.
버전 오류일 수도 있다고 생각이 드는데, 계속 씨름하다가 해결 못 하겠어서 이슈 올립니다. ㅠㅠ 

해결방법 아는 분들은 알려주시면 감사하겠습니다 (_ _)

**Comment by Beomi** [comment]
안녕하세요. 최근에 Huggingface Transformers가 버전이 4.0으로 올라갔는데요, 해당 부분에서 뭔가 바뀐게 있는 듯 하네요.
저도 한번 살펴보겠습니다.
제보 감사합니다 :)

**Comment by Beomi** [comment]
업데이트한 코드를 README에 추가하였습니다.

https://colab.research.google.com/drive/1dFC0FL-521m7CL_PSd8RLKq67jgTJVhL

위 코랩 링크(본문과 동일)에 코드를 업데이트해두었으니 잘 실행될 것입니다 :)

**Comment by woodongk** [comment]
@Beomi 빠르게 해결해주셔서 정말 감사합니다 :) 올려주신 코드 정말 잘 사용하고 있습니다! 감사합니다.
